### ISSUE TITLE
Support encode/decode for golang's native time.Time in addition to Timestamp

### ISSUE THREAD

**Issue by justing-bq** [amzn/ion-go#113]
Before we implemented Timestamp, we were using go's native time.Time type and supported encode/decode with it.

After https://github.com/amzn/ion-go/pull/98, that was all replaced with Timestamp.

It would be great if we could support encode/decode for both time.Time and Timestamp.

Look at the `marshal.go` and `unmarshal.go` changes in https://github.com/amzn/ion-go/pull/98 to see how we were encoding/decoding time.Time before Timestamp replaced it.

**Comment by Armanbqt** [comment]
Marshal/encode golang's native time.Time is merged in https://github.com/amzn/ion-go/pull/171

**Comment by byronlin13** [comment]
This issue isn't entirely fixed. We still don't have unmarshal support of Golang's native time
