### ISSUE TITLE
Implement missing cases for Float 

### ISSUE THREAD

**Issue by therapon** [amzn/ion-go#132]
Implement 

* NaN
* -Inf 
* +Inf

**Comment by Armanbqt** [comment]
The current state of library handles these special floats.
[Test in binary writer](https://github.com/amzn/ion-go/blob/master/ion/binarywriter_test.go#L213)    -     [test in binary writer](https://github.com/amzn/ion-go/blob/master/ion/binaryreader_test.go#L379)
[Test in text reader](https://github.com/amzn/ion-go/blob/master/ion/textreader_test.go#L285)     -    [test in text writer](https://github.com/amzn/ion-go/blob/master/ion/textwriter_test.go#L220)

Also the test on ion-test repository which tests ```[+inf -inf NaN]```: [floatSpecials.ion](
https://github.com/amzn/ion-tests/blob/master/iontestdata/good/floatSpecials.ion)
