### ISSUE TITLE
Unmarshal to native Time

### ISSUE THREAD

**Issue by icrustandi** [amzn/ion-go#174]
Hi, I just noticed that support for native go Time was most recently added to marshal. I was wondering if the same support could be added for the unmarshal as well. I looked at unmarshal.go and it seems like only ion.Timestamp is supported.
https://github.com/amzn/ion-go/blob/master/ion/unmarshal.go#L86

Currently the following happens:
```
		val, _ := ion.MarshalText(time.Now())
		result := new(time.Time)
		err = ion.Unmarshal(val, result) 
		// ion: cannot decode 0001-01-01 00:00:00 +0000 UTC into time.Time
```

**Comment by justing-bq** [comment]
This issue has been addressed and included in release [v1.1.3](https://github.com/amzn/ion-go/releases/tag/v1.1.3).
