### ISSUE TITLE
Unmarshaler interface

### ISSUE THREAD

**Issue by lindlof** [amzn/ion-go#184]
The `Marshaler` interface is provided for marshaling custom types to ion. However, no interface is provided for unmarshaling from ion. Is there some technical reason to not provide this?

It would be immensely helpful for building types which are interoperable with both ion and json. Specifically, we're looking to have decimal and timestamp types which are interoperable with both ion and json.

**Comment by fernomac** [comment]
As far as I remember (it's been a while), no I just never got around to it. 😅 Taking a quick look, I think it _should_ just be a matter of defining the interface and dropping something like [this](https://github.com/amzn/ion-go/blob/3f5d6c7f1616ca404a136803c1b08405d7a29b31/ion/marshal.go#L202) in [here](https://github.com/amzn/ion-go/blob/master/ion/unmarshal.go#L307)?

**Comment by errorhandler** [comment]
Just jumping into 👍🏻   the need for this, I've thrown together a quick branch [here](https://github.com/JasperLabs/ion-go/tree/unmarshal) that I'm happy to contribute back!

**Comment by desaikd** [comment]
Thanks for putting together a quick branch @errorhandler! Can you please create a pull request for this? It would be easier for us to review it over there.

**Comment by popematt** [comment]
I'm going to close this now that #185 has been merged. Thanks to @errorhandler for implementing this!
