### ISSUE TITLE
Implement isScalar() and isContainer() in type.go

### ISSUE THREAD

**Issue by justing-bq** [amzn/ion-go#34]
Can we get the following functions defined in type.go:

isScalar() should return true if the type is NullType, BoolType, IntType, FloatType, DecimalType, TimestampType, SymbolType, StringType, ClobType, or BlobType. Returns false otherwise.

isContainer() should return true if the type is ListType, SexpType, or StructType. Returns false otherwise.

**Comment by Armanbqt** [comment]
Similar logic in [ion-dotnet](https://github.com/amzn/ion-dotnet/blob/master/Amazon.IonDotnet/IonType.cs#L67)
