### ISSUE TITLE
Fix Decimal type issues

### ISSUE THREAD

**Issue by Armanbqt** [amzn/ion-go#36]
For values around decimal bounds (like ones in [decimal64BitBoundary](https://github.com/amzn/ion-tests/blob/05ecd5de78ac6244826cd4e77bae932925c966c1/iontestdata/good/decimal64BitBoundary.ion)), or big values of decimal, and decimals with underscore we cannot have a successful round trip.
Doing this should result in removing tests regarding Decimal from the skip lists.

**Comment by matthewh-BQ** [comment]
@zslayton : I believe this bucket task can be closed.

Looked more into the failing tests with the PR #51 , remaining of failing tests associated with issue #67.

Decimal support considers precision and different representations. For example:

Not Equal
```
// different precisions (negative zeroes)
[
    -0.,
    -0.0,
    -0.00,
    -0.000000,
]
```

Equal
```
(
    0.
    0d0
)
```

**Comment by Armanbqt** [comment]
Closing in favor of #67
