### ISSUE TITLE
Add a re-usable encoding buffer to binaryWriter

### ISSUE THREAD

**Issue by zslayton** [amzn/ion-go#57]
Each of `binaryWriter`'s `Write*` functions [call `make(byte[], ...)`](https://github.com/amzn/ion-go/blob/f53d5c7815980a7839ac3010863f88752c2e62b6/ion/binarywriter.go#L85), allocating a buffer of the appropriate size to hold the encoded value.

We should be able to get a good speedup by having a re-usable buffer of a reasonable capacity (say, 256 bytes?) that can be used for most scalars. Values that need more than 256 bytes (e.g. long `string`s) could fall back to allocating their own slice.

We shouldn't make this change without doing some before/after performance measurements.

**Comment by fernomac** [comment]
Watch out for the fact that “write” usually isn’t _actually_ writing the data you pass it through to the underlying io.Writer; it’s often holding on to the slices you pass it an in-memory tree structure that won’t get flushed out to the io.Writer until we’ve finalised the local symbol table and know the total size of all of the parent values being written. Reusing buffers before that happens will cause trouble. :(

**Comment by zslayton** [comment]
Thanks for clarifying, I had a different mental model of how the container lengths were being calculated. I'll close this out.

**Comment by fernomac** [comment]
(To be explicit: please feel free to change how the buffering/length calculations work if there's a better way to do it. I've got no reason to believe that the current approach is optimal and I haven't profiled it, it's just the first thing that I got to work. :))
