### ISSUE TITLE
Decimal Compare

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-go#6]
https://github.com/amzn/ion-go/blob/99ab8d02b0474c84a97f2e90fc4c0747299c50d4/ion/cmp_test.go#L188

Seems like non equivs vectors involving decimals shouldn't be passing based off the decimal compare impl. 
Why is all type comparison logic explicit functionality within the test file itself.

**Comment by mrutter-amzn** [comment]
The reason for custom comparison logic is that other methods either aren't able to handle private fields (GoCmp) or are brittle (reflect.DeepEqual).

**Comment by almann** [comment]
See my comment on #9 regarding decimals.  Specifically, this comparison is only used in testing and not exposed as part of our APIs.  That said, we can work around this for equivalence by making sure we do strict equivalence over the *coefficient* and *exponent* of the decimals we use.

I am closing this in favor of #9 as that tracks the primary issue of decimal fidelity.
