### ISSUE TITLE
Symbol Table Support

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-go#7]
https://github.com/amzn/ion-go/blob/99ab8d02b0474c84a97f2e90fc4c0747299c50d4/ion/cmp_test.go#L169

 what are the limitations?

**Comment by almann** [comment]
There is no user facing symbol table API, and we should definitely define one.  This is fundamentally a limitation in supporting shared symbol tables, but doesn't necessarily mean that local symbol tables per se are not supported.  Either way, we need define this API and be clear about how users work with symbols.

**Comment by wesboyt** [comment]
Going to close in favor of #11
