### ISSUE TITLE
Fix timestamp precision issue for imprecise timestamps

### ISSUE THREAD

**Issue by justing-bq** [amzn/ion-go#95]
The following input results in a test failure in ion-hash-test:

`{
    ion:2017T,
    expect:{
        identity:(update::(0x0b) update::(0x60) update::(0xc0 0x0f 0xe1) update::(0x0e) digest::(0x0b 0x60 0xc0 0x0f 0xe1 0x0e))
    }
}`

expected: [][]uint8{[]uint8{0xb}, []uint8{0x60}, []uint8{0xc0, 0xf, 0xe1}, []uint8{0xe}}
actual: [][]uint8{[]uint8{0xb}, []uint8{0x60}, []uint8{0x80, 0xf, 0xe1, 0x81, 0x81, 0x80, 0x80, 0x80}, []uint8{0xe}}

The reason for this is because the timestamp `2017T` is treated the same as `2017-01-01T00:00:00+00:00`

**Comment by Armanbqt** [comment]
Fixed in #98
