### ISSUE TITLE
Fix trailing 0xc1 timestamp issue

### ISSUE THREAD

**Issue by justing-bq** [amzn/ion-go#96]
The following input results in a test failure in ion-hash-test:

`timestampDistinct02::{
  '10n': (0x69 0x80 0x0f 0xd0 0x81 0x81 0x80 0x80 0x80 0xc1),
  expect:{ identity:(
    update::(0x0b)
    update::(0x60)
    update::(0x80 0x0f 0xd0 0x81 0x81 0x80 0x80 0x80 0xc1)
    update::(0x0e)
    digest::(0x0b 0x60 0x80 0x0f 0xd0 0x81 0x81 0x80 0x80 0x80 0xc1 0x0e)
  ) }
}`

expected: [][]uint8{[]uint8{0xb}, []uint8{0x60}, []uint8{0x80, 0xf, 0xd0, 0x81, 0x81, 0x80, 0x80, 0x80, 0xc1}, []uint8{0xe}}
actual  : [][]uint8{[]uint8{0xb}, []uint8{0x60}, []uint8{0x80, 0xf, 0xd0, 0x81, 0x81, 0x80, 0x80, 0x80}, []uint8{0xe}}

**Comment by therapon** [comment]
Is this related to #95?

**Comment by Armanbqt** [comment]
Fixed in #98
